# Generated by Django 5.2.12 on 2026-04-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_data',
            name='gender',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
