import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "CDA.settings")
django.setup()

from django.db import connection

sql = """
CREATE TABLE IF NOT EXISTS "user_cart" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "user_cartitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "product_id" integer NOT NULL, "product_name" varchar(200) NOT NULL, "product_price" numeric(10, 2) NOT NULL, "product_image" varchar(100) NULL, "quantity" integer NOT NULL CHECK ("quantity" >= 0), "cart_id" bigint NOT NULL);

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_cart_user_id_6e18b40e_fk_auth_user_id') THEN
        ALTER TABLE "user_cart" ADD CONSTRAINT "user_cart_user_id_6e18b40e_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_cartitem_cart_id_31cc1c28_fk_user_cart_id') THEN
        ALTER TABLE "user_cartitem" ADD CONSTRAINT "user_cartitem_cart_id_31cc1c28_fk_user_cart_id" FOREIGN KEY ("cart_id") REFERENCES "user_cart" ("id") DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "user_cartitem_cart_id_31cc1c28" ON "user_cartitem" ("cart_id");
"""

with connection.cursor() as cursor:
    cursor.execute(sql)

print("Tables created successfully.")
