# Generated by Django 5.2.12 on 2026-07-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Science', max_length=100)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='science_images')),
            ],
        ),
    ]
