# Generated by Django 5.2.12 on 2026-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
